language: haxe
sudo: false
haxe:
 - development

install:
 - haxelib install utest
 - haxelib git hxnodejs https://github.com/HaxeFoundation/hxnodejs

script:
 - haxe build.hxml --interp
 - haxe build.hxml -lib hxnodejs -js export/test.js --cmd "node export/test.js"