language: haxe
sudo: false
haxe:
 - development

install:
 - haxelib install utest
 - haxelib git json-rpc https://github.com/vshaxe/json-rpc

script:
 - haxe build.hxml --interp
 - haxe build.hxml -js export/test.js --cmd "node export/test.js"